# Generated by Django 4.2.2 on 2023-06-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=100)),
                ('japanese_name', models.CharField(default=True, max_length=100)),
                ('price', models.CharField(default=True, max_length=10)),
                ('description', models.CharField(default=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='appetizer',
            name='description',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appetizer',
            name='japanese_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appetizer',
            name='price',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='maincourse',
            name='description',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='maincourse',
            name='japanese_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='maincourse',
            name='price',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='appetizer',
            name='name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='maincourse',
            name='name',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
