# Generated by Django 4.2.2 on 2023-06-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0003_alter_appetizer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appetizer',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appetizer',
            name='japanese_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appetizer',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='japanese_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='maincourse',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maincourse',
            name='japanese_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maincourse',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maincourse',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
