# Generated by Django 4.2.2 on 2023-06-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0005_remove_appetizer_price_remove_dessert_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appetizer',
            name='price',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='dessert',
            name='price',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='maincourse',
            name='price',
            field=models.IntegerField(default=True),
        ),
    ]
