# Generated by Django 4.2.2 on 2023-06-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0006_appetizer_price_dessert_price_maincourse_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appetizer',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='maincourse',
            name='price',
            field=models.IntegerField(),
        ),
    ]
